################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/STM32CubeWs/STM32CubeL5/Middlewares/Third_Party/trustedfirmware/test/suites/crypto/crypto_tests_common.c \
C:/STM32CubeWs/STM32CubeL5/Middlewares/Third_Party/trustedfirmware/test/framework/test_framework.c \
C:/STM32CubeWs/STM32CubeL5/Middlewares/Third_Party/trustedfirmware/test/framework/test_framework_helpers.c 

OBJS += \
./Middlewares/trustedfirmware/test/crypto_tests_common.o \
./Middlewares/trustedfirmware/test/test_framework.o \
./Middlewares/trustedfirmware/test/test_framework_helpers.o 

C_DEPS += \
./Middlewares/trustedfirmware/test/crypto_tests_common.d \
./Middlewares/trustedfirmware/test/test_framework.d \
./Middlewares/trustedfirmware/test/test_framework_helpers.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/trustedfirmware/test/crypto_tests_common.o: C:/STM32CubeWs/STM32CubeL5/Middlewares/Third_Party/trustedfirmware/test/suites/crypto/crypto_tests_common.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DSTM32L562xx -DUSE_HAL_DRIVER -DSST_ENCRYPTION -DTFM_PSA_API '-DTFM_LVL=2' -DTFM_LEGACY_API -DBL2 -c -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/STM32L562E-DK -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/secure_fw/spm -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/secure_fw/core -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/secure_fw/services -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/interface/include -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/include -I../../../../../../../../Middlewares/Third_Party/trustedfirmware -I../../../NonSecure/Inc -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/test/suites/crypto -I../../../../Linker -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/lib/ext/qcbor/inc -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/secure_fw/core/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums  -funsigned-char   -msoft-float -fstack-usage -MMD -MP -MF"Middlewares/trustedfirmware/test/crypto_tests_common.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/trustedfirmware/test/test_framework.o: C:/STM32CubeWs/STM32CubeL5/Middlewares/Third_Party/trustedfirmware/test/framework/test_framework.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DSTM32L562xx -DUSE_HAL_DRIVER -DSST_ENCRYPTION -DTFM_PSA_API '-DTFM_LVL=2' -DTFM_LEGACY_API -DBL2 -c -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/STM32L562E-DK -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/secure_fw/spm -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/secure_fw/core -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/secure_fw/services -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/interface/include -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/include -I../../../../../../../../Middlewares/Third_Party/trustedfirmware -I../../../NonSecure/Inc -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/test/suites/crypto -I../../../../Linker -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/lib/ext/qcbor/inc -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/secure_fw/core/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums  -funsigned-char   -msoft-float -fstack-usage -MMD -MP -MF"Middlewares/trustedfirmware/test/test_framework.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Middlewares/trustedfirmware/test/test_framework_helpers.o: C:/STM32CubeWs/STM32CubeL5/Middlewares/Third_Party/trustedfirmware/test/framework/test_framework_helpers.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DSTM32L562xx -DUSE_HAL_DRIVER -DSST_ENCRYPTION -DTFM_PSA_API '-DTFM_LVL=2' -DTFM_LEGACY_API -DBL2 -c -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/STM32L562E-DK -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/secure_fw/spm -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/secure_fw/core -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/secure_fw/services -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/interface/include -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/include -I../../../../../../../../Middlewares/Third_Party/trustedfirmware -I../../../NonSecure/Inc -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/test/suites/crypto -I../../../../Linker -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/lib/ext/qcbor/inc -I../../../../../../../../Middlewares/Third_Party/trustedfirmware/secure_fw/core/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums  -funsigned-char   -msoft-float -fstack-usage -MMD -MP -MF"Middlewares/trustedfirmware/test/test_framework_helpers.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"

